alembic @ file:///croot/alembic_1666725231996/work
aniso8601 @ file:///tmp/build/80754af9/aniso8601_1614708839015/work
blinker @ file:///croot/blinker_1696539051175/work
Brotli @ file:///tmp/abs_ecyw11_7ze/croots/recipe/brotli-split_1659616059936/work
certifi @ file:///croot/certifi_1707229174982/work/certifi
cffi @ file:///croot/cffi_1700254295673/work
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1695468599471/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click @ file:///croot/click_1698129812380/work
cryptography @ file:///croot/cryptography_1707523700518/work
filetype==1.2.0
Flask @ file:///home/conda/feedstock_root/build_artifacts/flask_1707043907952/work
Flask-Cors @ file:///tmp/build/80754af9/flask-cors_1609957731919/work
Flask-Migrate @ file:///home/conda/feedstock_root/build_artifacts/flask-migrate_1694538503090/work
Flask-RESTful @ file:///home/conda/feedstock_root/build_artifacts/flask-restful_1684644040547/work
flask-sieve==2.0.1
Flask-SQLAlchemy @ file:///croot/flask-sqlalchemy_1671219118085/work
greenlet @ file:///croot/greenlet_1702059959679/work
idna @ file:///croot/idna_1666125576474/work
importlib-metadata @ file:///croot/importlib_metadata-suite_1704813515092/work
itsdangerous @ file:///home/conda/feedstock_root/build_artifacts/itsdangerous_1648147185463/work
Jinja2 @ file:///croot/jinja2_1706733616596/work
Mako @ file:///croot/mako_1665472421453/work
MarkupSafe @ file:///croot/markupsafe_1704205993651/work
mysqlclient @ file:///home/conda/feedstock_root/build_artifacts/mysqlclient_1709578079965/work
pillow==10.2.0
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyOpenSSL @ file:///croot/pyopenssl_1708380408460/work
PySocks @ file:///tmp/build/80754af9/pysocks_1605305812635/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-dotenv @ file:///home/conda/feedstock_root/build_artifacts/python-dotenv-split_1706018097647/work
pytz @ file:///croot/pytz_1695131579487/work
requests @ file:///croot/requests_1690400202158/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
SQLAlchemy @ file:///croot/sqlalchemy_1705089115293/work
typing_extensions @ file:///croot/typing_extensions_1705599297034/work
urllib3 @ file:///croot/urllib3_1698257533958/work
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1698235201373/work
zipp @ file:///croot/zipp_1704206909481/work
