apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - "../../base"
resources:
  # - "configmap.yaml"
  # - "sealed-secret.yaml"
images:
  - name: alekseykudr/game2048
    newTag: v1.2
# patchesJson6902:
#   - target:
#       group: apps
#       kind: Deployment
#       name: regulation-agent
#       version: v1
#     path: patch/deploy-patch.yaml
