# {
#   "kind": "SealedSecret",
#   "apiVersion": "bitnami.com/v1alpha1",
#   "metadata": {
#     "name": "regulation-agent-secret",
#     "namespace": "rcs-rebuild-dev",
#     "creationTimestamp": null
#   },
#   "spec": {
#     "template": {
#       "metadata": {
#         "name": "regulation-agent-secret",
#         "namespace": "rcs-rebuild-dev",
#         "creationTimestamp": null
#       },
#       "type": "Opaque"
#     },
#     "encryptedData": {
#       "DB_PASSWORD_READER": "AgAxoDRa7HkvWWUAvu4Ezopnzq5AQ2KkHjCl6fgWn3m3hQkLaTa7WyfSyv2KicfSVibV+OglkhyuajYrs1veEhcEONhXZaUHgSdnWbHPN6eoMWvfbf2DT7PsT9jWjPPEbMgoFPz18GT0xDXi29QttDZNER73rehOYOnluQN+68zWbnBJQWHXztUPaAOhqdqyBCdif2AaoQ18W3vj3VIH27fuc/vjmm8mvIPjZ4fscuxonXmxpns2J8EWOBsRfVLX+U5Uq0UMlebaSwd/BdtR6z9+wNstysLblAzuuNJDFNfCxGEEJ0uhi40b16qaEVPEch6fQhCJQhe3o2SbReDYhQaAdQtgN04PVjkDc2ngO47+qnCXtHgNngZBP2vUr6Fz203A4ERhGO4BsEmlkz5QSZcwQdCGXASXGrdcARUNeIOIOLc3BlW5qA+VA+sQ6/1Ch4OI2LvR5YlH5GoRBAonojXh5ezEsd9tMzMhvanpke79zKimeh7FYUx+Flpw0slwnHbC3214mPUhvJRkjEHwVX8DTEd20yQLoJVKWBQhVbTqcgHzI3PZxEVpgXL5VITOVx02mi5VDeo7CCCVd3Y0AHW2CTIN8gYJ3ZxW/3ZlCpVybN5LFPzX3VSNpWXeVF3s6FbgisTVJbTvG3lqEk7UW6dbVpzbqRdb5NiA0HKxn0epY9iRb+q0qWk/qMhc0oTvF4gZmw4SGY/wTqzDGYy7a3kWUgLEDQ==",
#       "DB_PASSWORD_WRITER": "AgCqwttWgl6dBQUvIwOnaKBa7k2xVqEK7y0jQNCgxpcZYI/dmZ3Bilbu54kXyHxHvhmWVa4wnm8i/4NDZv/NA0Rpqtl7PQB/1L2OFWzQPAukiebWlJKk4VRVAmwOwapG0XnhsS7BArKGdjOhmscCHysw8bLH6+h0QnBrxi1/E4nSL4ChHKR24zkuYKqbPpl+VQ20UeSQX5HSP9lZ8Rthj7zUEus2bDLQrtAtgparvMktltLHlTNSGPlHUg7h6ym76dS9OhljiYGvoDOvz4lVrrrfegg5ZxAewbMFwrhO7nBnmMsmhuunKhT0YFOuEOGy7g/b6ADdCIcghuvIbWktNtS5rnPyXbC1CvFwH80KewgqNnXk2db3z1G6LdRzULvJLtRcZm2QK9euW0/u0LDDwa1xgzDbL1r0CveNgHhM3B3/lwgQYjHhd4mZ/UAS30T8Y3u99kzjGVCNBC3r2b0EtfS1jvCOGPb7CaleKFjCSUbZecVNyCOCIsJZzb0CV+NfkD9G/s0+UNCpqMZ0lx+CeQvWJfkhKIkzd+4cr+130gGL7TUgeTcMM557FJ9/qPPkGNqZ5mUiVLRoskHJVC8i09fCL2fBGpjfqQTvGvqTeXlc5NCq+jYVmtnGXHI7j7xTA1rNg6FUwX7Uqp9/GVGbPlC0QB2eeDuwcVnfeGqdxfwGW9O/sHoS+iczn5VmkNdq62JHa8zfPeWTV7iSvbJ1V5ehRBNj7A=="
#     }
#   }
# }
