apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rcs-rebuild-dev
bases:
  - "nginx.yaml"
resources:
  - "../../service/config/overlays/develop"
  - "../../service/game2048/overlays/develop"