apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game2048-ingress
spec:
  rules:
  - host: game2048.shamirhusein.my.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game2048-svc
            port: 
              number: 80
  ingressClassName: nginx